name: json_stream
description: Encode and Decode JSON in streams ot increase performance
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  characters:
  channel:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.7
